name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions
on:
  push:
  workflow_dispatch:
jobs:
  Explore-GitHub-Actions:
    runs-on: self-hosted
    steps:
      - run: echo "The job was automatically triggered by a ${{ secrets.MY }} event."
      - run: echo "The job was automatically triggered by a ${{ runner.os }} event."
      
